from __future__ import annotations

from pathlib import Path
import py_compile

from reverie.agent.tool_descriptions import get_tool_descriptions_for_mode
from reverie.agent.tool_executor import ToolExecutor
from reverie.engine_lite.blender_modeling import (
    create_blender_authoring_job,
    infer_blender_preset,
    validate_blender_script_text,
)
from reverie.tools.blender_modeling_workbench import BlenderModelingWorkbenchTool


def test_blender_authoring_job_generates_auditable_script(tmp_path: Path) -> None:
    job = create_blender_authoring_job(
        tmp_path,
        brief="fantasy crystal shrine relic with orbiting rings",
        model_name="Shrine Relic",
        overwrite=True,
    )

    script_path = Path(job["paths"]["script"])
    plan_path = Path(job["paths"]["plan"])

    assert job["spec"]["preset"] == "fantasy_relic"
    assert script_path.exists()
    assert plan_path.exists()
    assert job["relative_paths"]["script"] == "assets/models/source/blender/scripts/shrine_relic.py"

    script_text = script_path.read_text(encoding="utf-8")
    assert "bpy.ops.wm.save_as_mainfile" in script_text
    assert "bpy.ops.export_scene.gltf" in script_text
    assert "Generated by Reverie CLI" in script_text
    assert "uvx" not in script_text

    py_compile.compile(str(script_path), doraise=True)


def test_blender_workbench_tool_can_generate_without_running_blender(tmp_path: Path) -> None:
    tool = BlenderModelingWorkbenchTool({"project_root": tmp_path})

    result = tool.execute(
        action="create_model",
        model_name="Sci Crate",
        brief="sci-fi crate with emissive panels",
        run_blender=False,
        overwrite=True,
    )

    assert result.success is True
    assert "Blender run: skipped" in result.output
    assert result.data["spec"]["preset"] == "sci_fi_crate"
    assert (tmp_path / "assets/models/source/blender/scripts/sci_crate.py").exists()
    assert (tmp_path / "data/models/model_registry.yaml").exists()


def test_blender_anime_action_character_preset_builds_richer_blockout(tmp_path: Path) -> None:
    job = create_blender_authoring_job(
        tmp_path,
        brief="Genshin / ZZZ style anime action playable character with jacket, weapon, rig markers",
        model_name="Neon Duelist",
        overwrite=True,
    )

    assert job["spec"]["preset"] == "anime_action_character"
    assert job["spec"]["style"] == "anime_action"
    assert job["spec"]["quality_targets"]["rig_and_lod_markers"] is True

    script_path = Path(job["paths"]["script"])
    script_text = script_path.read_text(encoding="utf-8")
    assert "build_anime_action_character" in script_text
    assert "stylized_energy_blade_lod0" in script_text
    assert "rig_marker_head" in script_text

    py_compile.compile(str(script_path), doraise=True)


def test_blender_production_character_pipeline_builds_full_authoring_stack(tmp_path: Path) -> None:
    job = create_blender_authoring_job(
        tmp_path,
        brief="AAA final character asset with high poly sculpt, retopo, UV unwrap, texture bake, rigged animation set",
        model_name="Aurora Vanguard",
        overwrite=True,
    )

    assert job["spec"]["preset"] == "production_character_pipeline"
    assert job["spec"]["quality_targets"]["high_poly_collection"] is True
    assert job["spec"]["quality_targets"]["retopo_low_collection"] is True
    assert job["spec"]["quality_targets"]["uv_layout"] is True
    assert job["spec"]["quality_targets"]["texture_exports"] is True
    assert job["spec"]["quality_targets"]["skeletal_rig"] is True
    assert job["spec"]["quality_targets"]["animation_actions"] is True
    assert job["spec"]["quality_targets"]["ik_control_markers"] is True
    assert job["spec"]["quality_targets"]["lod_variants"] is True
    assert job["spec"]["quality_targets"]["vertex_group_weights"] is True
    assert job["spec"]["quality_targets"]["asset_validation_report"] is True

    script_path = Path(job["paths"]["script"])
    script_text = script_path.read_text(encoding="utf-8")
    assert "build_production_character_pipeline" in script_text
    assert "create_texture_placeholders" in script_text
    assert "create_humanoid_rig" in script_text
    assert "assign_runtime_vertex_groups" in script_text
    assert "create_lod_variants" in script_text
    assert "create_rig_control_markers" in script_text
    assert "validate_runtime_character_asset" in script_text
    assert "character_idle_preview" in script_text
    assert "create_expression_shape_keys" in script_text
    assert "create_attachment_sockets" in script_text
    assert "create_turntable_camera_animation" in script_text
    assert "retopo_low" in script_text
    assert str(job["paths"]["texture_basecolor"]).endswith("aurora_vanguard_basecolor.png")
    assert str(job["paths"]["texture_id"]).endswith("aurora_vanguard_id.png")
    assert str(job["paths"]["validation_report"]).endswith("aurora_vanguard_validation.json")

    py_compile.compile(str(script_path), doraise=True)


def test_blender_script_validation_blocks_unsafe_modules() -> None:
    ok, issues = validate_blender_script_text("import bpy\nimport socket\nbpy.ops.object.select_all()\n")

    assert ok is False
    assert "blocked import: socket" in issues


def test_blender_tool_is_visible_and_prompted_in_reverie_and_gamer(tmp_path: Path) -> None:
    executor = ToolExecutor(project_root=tmp_path)

    reverie_names = {item["function"]["name"] for item in executor.get_tool_schemas(mode="reverie")}
    gamer_names = {item["function"]["name"] for item in executor.get_tool_schemas(mode="reverie-gamer")}
    reverie_prompt = get_tool_descriptions_for_mode("reverie")
    gamer_prompt = get_tool_descriptions_for_mode("reverie-gamer")

    assert "blender_modeling_workbench" in reverie_names
    assert "blender_modeling_workbench" in gamer_names
    assert "rc_blender_ensure_runtime" in reverie_prompt
    assert "direct Blender authoring" in gamer_prompt


def test_blender_preset_inference_handles_chinese_modeling_briefs() -> None:
    assert infer_blender_preset("制作一个魔法水晶祭坛和环绕光环") == "fantasy_relic"
    assert infer_blender_preset("制作一个科幻机甲补给箱") == "sci_fi_crate"


def test_blender_preset_inference_handles_anime_action_character_refs() -> None:
    assert infer_blender_preset("\u539f\u795e\u98ce\u683c\u7684\u4e8c\u6e38\u4eba\u7269\u5efa\u6a21") == "anime_action_character"
    assert infer_blender_preset("ZZZ style AAA character with weapon") == "anime_action_character"


def test_blender_preset_inference_prioritizes_production_character_pipeline_refs() -> None:
    assert infer_blender_preset("3A final character asset with high poly retopo UV bake and rigging") == "production_character_pipeline"
    assert infer_blender_preset("\u6700\u7ec8\u89d2\u8272\u8d44\u4ea7\uff0c\u9700\u8981\u9ad8\u6a21\u3001\u62d3\u6251\u3001UV\u3001\u6743\u91cd\u548c\u52a8\u4f5c") == "production_character_pipeline"
