"""Shared command-help catalog for Reverie CLI."""

from __future__ import annotations

from typing import Dict, List


HELP_SECTION_ORDER: List[str] = [
    "Core",
    "Models & Modes",
    "Providers",
    "Tools & Context",
    "Sessions & Recovery",
    "Project & Rules",
    "Game",
]


HELP_TOPICS: Dict[str, Dict[str, object]] = {
    "help": {
        "command": "/help",
        "section": "Core",
        "summary": "Browse the live help catalog, pin a detailed page, or print the full reference.",
        "detail": "Bare `/help` opens the interactive browser. Press Enter or Esc to pin the current command panel into the transcript; `/help <command>` prints one detailed page and `/help all` prints the whole catalog.",
        "overview": "browser, <command>, all",
        "subcommands": [
            {"usage": "/help", "description": "Open the interactive help browser with live navigation, filtering, and detailed command pages."},
            {"usage": "/help <command>", "description": "Show detailed help for a single command such as `/help codex` or `/help Geminicli model`.", "example": "/help Geminicli model"},
            {"usage": "/help all", "description": "Print the detailed help view for every command in sequence."},
        ],
        "examples": ["/help", "/help codex", "/help Geminicli model", "/help all"],
    },
    "status": {
        "command": "/status",
        "section": "Core",
        "summary": "Show the active model, provider source, session, and runtime health.",
        "detail": "This is the fast health check for the current session, active model selection, indexing state, and token headroom.",
        "overview": "status snapshot",
        "subcommands": [
            {"usage": "/status", "description": "Show the current model, endpoint, source, session, index, and uptime status."},
        ],
        "examples": ["/status"],
    },
    "doctor": {
        "command": "/doctor",
        "section": "Core",
        "summary": "Audit the active workspace's harness readiness across goals, context, tools, execution, memory, evaluation, and recovery.",
        "detail": "This is the harness-level health check inspired by execution-first coding CLIs. It summarizes the task ledger, tool surface, command audit history, operation history, checkpoints, sessions, and recommendations for tightening the workflow shell around the model.",
        "overview": "doctor, json, history",
        "aliases": ["/harness"],
        "subcommands": [
            {"usage": "/doctor", "description": "Show the formatted harness audit dashboard for the current workspace."},
            {"usage": "/doctor json", "description": "Print the same harness audit as structured JSON."},
            {"usage": "/doctor history", "description": "Show recent prompt-run harness history and score/verification trends."},
            {"usage": "/harness", "description": "Alias of `/doctor`."},
        ],
        "examples": ["/doctor", "/doctor json", "/doctor history", "/harness"],
    },
    "clear": {
        "command": "/clear",
        "section": "Core",
        "summary": "Clear the current terminal view without touching session state.",
        "detail": "Only the screen is cleared. Conversation history, sessions, and config stay intact.",
        "overview": "clear screen",
        "subcommands": [
            {"usage": "/clear", "description": "Clear the terminal output."},
        ],
        "examples": ["/clear"],
    },
    "clean": {
        "command": "/clean",
        "section": "Core",
        "summary": "Delete current-workspace memory, caches, checkpoints, and command audit history, then start fresh.",
        "detail": "Only the active workspace is affected. Reverie removes the current workspace's cache under the app root at `.reverie/project_caches/<project-key>/` and also cleans legacy workspace-local `.reverie/context_cache` or `.reverie/security` folders when they still exist; config and rules remain intact.",
        "overview": "reset workspace memory, force",
        "subcommands": [
            {"usage": "/clean", "description": "Prompt for confirmation, then delete current-workspace sessions, caches, checkpoints, and audit logs."},
            {"usage": "/clean force", "description": "Run the same cleanup without the confirmation prompt."},
        ],
        "examples": ["/clean", "/clean force"],
    },
    "exit": {
        "command": "/exit",
        "section": "Core",
        "summary": "Exit Reverie with a confirmation prompt.",
        "detail": "The current session is preserved; `/quit` is a direct alias of `/exit`.",
        "overview": "exit, quit",
        "aliases": ["/quit"],
        "subcommands": [
            {"usage": "/exit", "description": "Prompt for confirmation, then exit Reverie."},
            {"usage": "/quit", "description": "Alias of `/exit`."},
        ],
        "examples": ["/exit", "/quit"],
    },
    "model": {
        "command": "/model",
        "section": "Models & Modes",
        "summary": "Open the standard model selector or manage configured standard models.",
        "detail": "This catalog is separate from provider-native catalogs like `/codex model` or `/Geminicli model`.",
        "overview": "selector, add, delete/remove <n>",
        "subcommands": [
            {"usage": "/model", "description": "Open the selector for standard configured models."},
            {"usage": "/model add", "description": "Launch the interactive flow for adding a standard model configuration."},
            {"usage": "/model delete <number>", "description": "Delete a configured standard model by its selector index."},
            {"usage": "/model remove <number>", "description": "Alias of `/model delete <number>`."},
        ],
        "examples": ["/model", "/model add", "/model delete 2"],
    },
    "subagent": {
        "command": "/subagent",
        "section": "Models & Modes",
        "summary": "Create, inspect, and run base-Reverie Subagents with a selected default model.",
        "detail": "Subagents are only enabled in base `reverie` mode. Each Subagent is identified by its ID, stores a selected default model, and inherits the active Reverie prompt, tools, plugins, MCP surface, and skills when the main agent delegates a task.",
        "overview": "selector, create, list, model <id>, run <id> <task>, delete <id>",
        "aliases": ["/subagents"],
        "subcommands": [
            {"usage": "/subagent", "description": "Open the configured Subagent roster TUI."},
            {"usage": "/subagent create", "description": "Open the model selector and create a new Subagent with that default model."},
            {"usage": "/subagent list", "description": "Show configured Subagents, colors, model sources, and IDs."},
            {"usage": "/subagent model <id>", "description": "Open the model selector and update one Subagent's default model."},
            {"usage": "/subagent run <id> <task>", "description": "Run a direct delegated task through a configured Subagent."},
            {"usage": "/subagent delete <id>", "description": "Delete a configured Subagent."},
        ],
        "examples": ["/subagent create", "/subagent list", "/subagent run subagent-001 create a short test file"],
    },
    "mode": {
        "command": "/mode",
        "section": "Models & Modes",
        "summary": "Show or switch Reverie operating modes.",
        "detail": "All modes share Context Engine. The selected mode changes the workflow, specialized tools, and delivery style.",
        "overview": "show, reverie|reverie-atlas|reverie-gamer|spec-driven|spec-vibe|writer|reverie-ant|computer-controller",
        "subcommands": [
            {"usage": "/mode", "description": "Show the current mode and the full mode table."},
            {"usage": "/mode reverie", "description": "Switch to the general-purpose coding mode."},
            {"usage": "/mode reverie-atlas", "description": "Switch to the document-driven spec development mode for complex systems."},
            {"usage": "/mode reverie-gamer", "description": "Switch to the game-development mode."},
            {"usage": "/mode spec-driven", "description": "Switch to the spec authoring mode."},
            {"usage": "/mode spec-vibe", "description": "Switch to the lighter spec implementation mode."},
            {"usage": "/mode writer", "description": "Switch to the writing and narrative continuity mode."},
            {"usage": "/mode reverie-ant", "description": "Switch to the long-running execution and verification mode."},
            {"usage": "/mode computer-controller", "description": "Switch to the pinned NVIDIA desktop-autopilot mode."},
        ],
        "examples": ["/mode", "/mode reverie-atlas", "/mode computer-controller"],
    },
    "geminicli": {
        "command": "/Geminicli",
        "section": "Providers",
        "summary": "Manage Gemini CLI OAuth relay status, models, and endpoint override.",
        "detail": "Personal Google-account login works directly through Gemini CLI. A project override can still be stored for advanced setups, but it is optional.",
        "overview": "status, login, model [id], endpoint [value]",
        "aliases": ["/geminicli"],
        "subcommands": [
            {"usage": "/Geminicli", "description": "Show Gemini CLI credential, model, and optional project-override status."},
            {"usage": "/Geminicli status", "description": "Explicit status view."},
            {"usage": "/Geminicli login", "description": "Validate or refresh Gemini OAuth credentials from the local CLI cache."},
            {"usage": "/Geminicli model", "description": "Open the Gemini CLI model selector."},
            {"usage": "/Geminicli model <model-id>", "description": "Switch directly to a supported Gemini CLI model."},
            {"usage": "/Geminicli endpoint", "description": "Show the current endpoint override prompt."},
            {"usage": "/Geminicli endpoint <url|/path|clear>", "description": "Set or clear the reverse-proxy endpoint override."},
        ],
        "examples": ["/Geminicli", "/Geminicli model gemini-3.1-flash-lite-preview", "/Geminicli endpoint http://127.0.0.1:8000/v1internal:streamGenerateContent?alt=sse"],
    },
    "codex": {
        "command": "/codex",
        "section": "Providers",
        "summary": "Switch to Codex, choose a model, and set the matching four-level reasoning depth.",
        "detail": "Bare `/codex` switches Reverie to the Codex source and uses the stored Codex model. `/codex model` opens the model selector and immediately continues into the reasoning-depth selector. `/codex endpoint` accepts either a proxy root/base URL or a full `/responses` endpoint.",
        "overview": "activate, login, model [id], thinking [level], endpoint [value], low|medium|high|extra high",
        "subcommands": [
            {"usage": "/codex", "description": "Switch Reverie to the Codex source and show the active Codex configuration."},
            {"usage": "/codex login", "description": "Validate or refresh Codex credentials from the local CLI cache."},
            {"usage": "/codex model", "description": "Open the Codex model selector, then continue into reasoning-depth selection."},
            {"usage": "/codex model <model-id>", "description": "Switch directly to a supported Codex model and keep its compatible reasoning depth."},
            {"usage": "/codex thinking", "description": "Open the reasoning-depth selector for the current Codex model."},
            {"usage": "/codex thinking <low|medium|high|extra high>", "description": "Set the reasoning depth explicitly."},
            {"usage": "/codex low|medium|high|extra high", "description": "Direct shortcut for reasoning-depth selection."},
            {"usage": "/codex endpoint", "description": "Show the current endpoint override prompt."},
            {"usage": "/codex endpoint <url|/path|clear>", "description": "Set or clear the reverse-proxy endpoint override."},
        ],
        "examples": ["/codex", "/codex model", "/codex model gpt-5.4", "/codex extra high"],
    },
    "nvidia": {
        "command": "/nvidia",
        "section": "Providers",
        "summary": "Configure the NVIDIA source, including mixed-transport models and the API key used by Reverie.",
        "detail": "Use this to save the NVIDIA API key, inspect the active NVIDIA setup, switch between supported models, toggle the GLM fast profile, or override the endpoint for reverse proxies. Reverie also reads `NVIDIA_API_KEY` automatically when present, and Computer Controller mode pins the runtime to `qwen/qwen3.5-397b-a17b`. Request-based vision models can also accept inline `@image.png` attachments in chat.",
        "overview": "status, key, activate, model [id], endpoint [value], fast [on|off]",
        "subcommands": [
            {"usage": "/nvidia", "description": "Show the current NVIDIA source configuration."},
            {"usage": "/nvidia key", "description": "Prompt for and save the NVIDIA API key from build.nvidia.com/settings/api-keys."},
            {"usage": "/nvidia activate", "description": "Switch the active model source to NVIDIA."},
            {"usage": "/nvidia model", "description": "Open the NVIDIA model selector."},
            {"usage": "/nvidia model <model-id>", "description": "Switch directly to a supported NVIDIA model."},
            {"usage": "/nvidia thinking max|high|off", "description": "Set thinking depth for NVIDIA models that expose provider-side effort control."},
            {"usage": "/nvidia fast on", "description": "Enable the GLM-5.1 fast interactive profile."},
            {"usage": "/nvidia fast off", "description": "Disable the GLM fast profile for deliberate deep-thinking runs."},
            {"usage": "/nvidia endpoint", "description": "Show the current endpoint override prompt."},
            {"usage": "/nvidia endpoint <url|/path|clear>", "description": "Set or clear the endpoint override."},
        ],
        "examples": ["/nvidia", "/nvidia thinking max", "/nvidia key", "/nvidia activate", "/nvidia endpoint https://integrate.api.nvidia.com/v1/chat/completions"],
    },
    "modelscope": {
        "command": "/modelscope",
        "section": "Providers",
        "summary": "Configure the ModelScope source that calls ModelScope API-Inference through the Anthropic SDK.",
        "detail": "Use this to save a ModelScope token, activate the source, pick a supported ModelScope model id, or override the Anthropic SDK base URL. Reverie reads `MODELSCOPE_API_KEY`, `MODELSCOPE_TOKEN`, or `MODELSCOPE_ACCESS_TOKEN` automatically when present. The default model is `ZhipuAI/GLM-5.1`.",
        "overview": "status, key, activate, model [id], endpoint [value]",
        "subcommands": [
            {"usage": "/modelscope", "description": "Show the current ModelScope source configuration."},
            {"usage": "/modelscope key", "description": "Prompt for and save the ModelScope token from modelscope.cn/my/access/token."},
            {"usage": "/modelscope activate", "description": "Switch the active model source to ModelScope."},
            {"usage": "/modelscope model", "description": "Open the ModelScope model selector."},
            {"usage": "/modelscope model <model-id>", "description": "Switch directly to a supported ModelScope model id."},
            {"usage": "/modelscope endpoint", "description": "Show the current Anthropic base URL prompt."},
            {"usage": "/modelscope endpoint <url|clear>", "description": "Set or clear the Anthropic SDK base URL."},
        ],
        "examples": ["/modelscope", "/modelscope key", "/modelscope activate", "/modelscope model ZhipuAI/GLM-5.1", "/modelscope endpoint https://api-inference.modelscope.cn"],
    },
    "tools": {
        "command": "/tools",
        "section": "Tools & Context",
        "summary": "Browse the live, mode-aware tool surface with search, recommendations, groups, and schema inspection.",
        "detail": "Tool visibility changes with the active mode, provider setup, and model capabilities. `/tools` uses the same discovery catalog the model uses internally, with detailed current-mode and all-mode inventory views.",
        "overview": "overview, search <query>, recommend <task>, inspect <tool>, groups, --mode <mode>",
        "subcommands": [
            {"usage": "/tools", "description": "Show the current mode's visible tools, quick picks, grouping summaries, and shortcuts."},
            {"usage": "/tools all", "description": "Show every loaded tool across modes with mode visibility, required fields, parameters, and descriptions."},
            {"usage": "/tools details", "description": "Show detailed tool information for the current or selected mode."},
            {"usage": "/tools search <query>", "description": "Search visible tools by keywords, aliases, tags, and parameter names.", "example": "/tools search telemetry vertical slice"},
            {"usage": "/tools recommend <task>", "description": "Get intent-ranked tool suggestions for a short task description.", "example": "/tools recommend inspect MCP docs"},
            {"usage": "/tools inspect <tool>", "description": "Inspect one tool or alias, including supported modes and schema.", "example": "/tools inspect shell"},
            {"usage": "/tools groups", "description": "Summarize the visible tools by category and runtime kind."},
            {"usage": "/tools --mode <mode>", "description": "Preview another mode's tool surface without switching the current session.", "example": "/tools --mode reverie-gamer"},
        ],
        "examples": ["/tools", "/tools all", "/tools details --mode reverie", "/tools search blueprint", "/tools recommend read MCP resources", "/tools inspect tool_catalog", "/tools groups", "/tools --mode writer"],
    },
    "skills": {
        "command": "/skills",
        "section": "Tools & Context",
        "summary": "Inspect OpenAI Codex-style `SKILL.md` discovery, roots, and injected instruction packs.",
        "detail": "Reverie loads skills only from the application root under `.reverie/Skills` or `.reverie/skills` beside the executable. Nested repository layouts like `<repo>/skills/<skill>/SKILL.md` are supported when they live under that `.reverie` tree. Detected skills are exposed in `/skills`, described in the system prompt, and can be activated explicitly with `$skill-name` or auto-selected when the request clearly matches a skill.",
        "overview": "status, rescan, path, inspect <skill-name>",
        "subcommands": [
            {"usage": "/skills", "description": "Show the detected skill summary and table."},
            {"usage": "/skills status", "description": "Explicit status view."},
            {"usage": "/skills rescan", "description": "Rescan the application `.reverie` skill roots and refresh prompt guidance."},
            {"usage": "/skills path", "description": "Show the scanned skill roots."},
            {"usage": "/skills inspect <skill-name>", "description": "Show one skill's metadata and a `SKILL.md` preview."},
        ],
        "examples": ["/skills", "/skills rescan", "/skills path", "/skills inspect openai-docs"],
    },
    "plugins": {
        "command": "/plugins",
        "section": "Tools & Context",
        "summary": "Inspect the portable SDK/runtime depot under `.reverie/plugins`.",
        "detail": "Plugins are now positioned as Reverie's local SDK depot rather than another Skill/MCP-like prompt feature. `.reverie/plugins/<plugin-id>/runtime` and `.reverie/plugins/<plugin-id>/source` are where heavyweight open runtimes such as Blender, Godot, O3DE, or validators can live beside the executable. Plugins may still expose optional `rc_*` dynamic tools when a runnable entry supports the Reverie CLI `-RC` protocol, and `/plugins templates` remains available for authoring those wrappers.",
        "overview": "status, rescan, path, sdk [plugin-id], inspect <plugin-id>, scaffold <plugin-id>, validate <plugin-id>, build <plugin-id>, templates, template inspect <template-id>",
        "subcommands": [
            {"usage": "/plugins", "description": "Show the SDK/runtime plugin summary and detected runtime table."},
            {"usage": "/plugins status", "description": "Explicit status view."},
            {"usage": "/plugins rescan", "description": "Rescan `.reverie/plugins` and refresh runtime detection."},
            {"usage": "/plugins path", "description": "Show the source root, SDK/install root, bundled runtime catalog code path, and template root."},
            {"usage": "/plugins sdk", "description": "List known portable SDK/runtime depots and their readiness."},
            {"usage": "/plugins sdk <plugin-id>", "description": "Prepare `.reverie/plugins/<plugin-id>/runtime` and write an SDK manifest."},
            {"usage": "/plugins inspect <plugin-id>", "description": "Show the detected `-RC` protocol metadata, command list, and tool exposure for one plugin."},
            {"usage": "/plugins scaffold <plugin-id>", "description": "Create a new source plugin tree when local plugin templates are installed."},
            {"usage": "/plugins validate <plugin-id>", "description": "Validate one source plugin's manifest, runtime handshake, and build prerequisites."},
            {"usage": "/plugins build <plugin-id> [install]", "description": "Run one source plugin's declared build commands and optionally sync it into `.reverie/plugins`."},
            {"usage": "/plugins templates", "description": "List the available runtime-plugin source templates."},
            {"usage": "/plugins template inspect <template-id>", "description": "Inspect one template, including manifest and entry previews."},
        ],
        "examples": ["/plugins", "/plugins sdk", "/plugins sdk blender", "/plugins deploy blender", "/plugins run blender", "/plugins inspect blender", "/plugins inspect godot", "/plugins validate blender", "/plugins build blender install", "/plugins templates"],
    },
    "mcp": {
        "command": "/mcp",
        "section": "Tools & Context",
        "summary": "Open the MCP control panel or manage MCP servers directly from commands.",
        "detail": "Bare `/mcp` opens an interactive panel similar to `/setting`, with live MCP state, quick toggles, discovery refresh, and server add/remove flows. Reverie now stores MCP settings beside the executable in `.\\.reverie\\mcp.json` using a standard top-level `mcpServers` layout, while still loading legacy `.\\.Reverie\\MCP.json` files for compatibility. `url` follows the legacy SSE transport and `httpUrl` follows streamable HTTP, matching common MCP client conventions. Reverie-Gamer now seeds a built-in `ashfox` MCP server entry automatically.",
        "overview": "panel/ui, status, reload, add stdio/http/sse, remove, enable, disable, trust, path",
        "subcommands": [
            {"usage": "/mcp", "description": "Open the interactive MCP control panel."},
            {"usage": "/mcp status", "description": "Print a static MCP status table without entering the panel."},
            {"usage": "/mcp reload", "description": "Reload `.reverie/mcp.json` (or a legacy MCP file) and refresh the discovered MCP catalog."},
            {"usage": "/mcp path", "description": "Show the active MCP configuration file path."},
            {"usage": "/mcp add <name> <command...>", "description": "Add a stdio MCP server, matching Gemini CLI's default add flow."},
            {"usage": "/mcp add stdio <name> <command...>", "description": "Explicit stdio variant of the add flow."},
            {"usage": "/mcp add http <name> <url>", "description": "Add a streamable HTTP MCP server."},
            {"usage": "/mcp add sse <name> <url>", "description": "Add a legacy SSE MCP server that exposes an endpoint event and message POST URL."},
            {"usage": "/mcp remove <name>", "description": "Remove a configured MCP server."},
            {"usage": "/mcp enable <name>", "description": "Enable a configured MCP server."},
            {"usage": "/mcp disable <name>", "description": "Disable a configured MCP server."},
            {"usage": "/mcp trust <name> on|off", "description": "Mark a server as trusted or confirmation-required."},
        ],
        "examples": ["/mcp", "/mcp add filesystem npx -y @modelcontextprotocol/server-filesystem .", "/mcp add http internal-api http://127.0.0.1:8080/mcp", "/mcp add sse legacy-api http://127.0.0.1:8081/sse", "/mcp trust filesystem on"],
    },
    "search": {
        "command": "/search",
        "section": "Tools & Context",
        "summary": "Run a web search and render the result as formatted output.",
        "detail": "Use this when you want an explicit web lookup rather than relying on model memory.",
        "overview": "<query>",
        "subcommands": [
            {"usage": "/search <query>", "description": "Search the web for the given query and show the top extracted results."},
        ],
        "examples": ["/search rust async patterns", "/search latest sqlite wal mode docs"],
    },
    "index": {
        "command": "/index",
        "section": "Tools & Context",
        "summary": "Rebuild the code index for the current workspace.",
        "detail": "Useful after large file changes when you want the symbol and dependency index refreshed immediately.",
        "overview": "full reindex",
        "subcommands": [
            {"usage": "/index", "description": "Run a full codebase re-index and report scan statistics."},
        ],
        "examples": ["/index"],
    },
    "ce": {
        "command": "/CE",
        "section": "Tools & Context",
        "summary": "Inspect or manage the Context Engine state.",
        "detail": "This command is case-sensitive. Automatic session rotation now handles large-context continuity by default; `/CE` remains useful for inspection and manual recovery operations.",
        "overview": "status, compress, info, stats",
        "subcommands": [
            {"usage": "/CE", "description": "Show Context Engine status, token usage, and available actions."},
            {"usage": "/CE compress", "description": "Compress the current conversation context."},
            {"usage": "/CE info", "description": "Show message counts, system-prompt length, and mode details."},
            {"usage": "/CE stats", "description": "Show full token statistics from the token counter tool."},
        ],
        "examples": ["/CE", "/CE compress", "/CE stats"],
    },
    "tti": {
        "command": "/tti",
        "section": "Tools & Context",
        "summary": "Generate images from configured local models and manage the local TTI runtime from one command namespace.",
        "detail": "Bare `/tti` needs a child action or prompt. `/tti source` now stays on the local runtime, and local model entries live in `text_to_image.models`.",
        "overview": "models, source [local], add, <prompt>",
        "subcommands": [
            {"usage": "/tti models", "description": "Open the selector for configured local TTI models and change the default image model."},
            {"usage": "/tti source", "description": "Show or confirm the active TTI source (`local`)."},
            {"usage": "/tti source <local>", "description": "Set the active TTI source directly."},
            {"usage": "/tti add", "description": "Add a new local text-to-image model entry to the config."},
            {"usage": "/tti <prompt>", "description": "Generate one image using the active local TTI source and its default model."},
        ],
        "examples": ["/tti source local", "/tti models", "/tti add", "/tti cyberpunk rainy alley concept art"],
    },
    "setting": {
        "command": "/setting",
        "section": "Project & Rules",
        "summary": "Open the settings dashboard or change runtime settings directly from the command line.",
        "detail": "The settings system now supports both a richer TUI and direct subcommands for mode, model, theme, transcript display, thinking visibility, API, workspace, and rules controls. `/settings` is a direct alias of `/setting`.",
        "overview": "ui, status, mode, model, theme, auto-index, status-line, tool-output, thinking, stream, timeout, retries, debug, workspace, rules",
        "aliases": ["/settings"],
        "subcommands": [
            {"usage": "/setting", "description": "Open the interactive settings interface with keyboard navigation and live detail panels.", "example": "/setting"},
            {"usage": "/settings", "description": "Alias of `/setting`.", "example": "/settings"},
            {"usage": "/setting ui", "description": "Explicitly open the interactive settings interface.", "example": "/setting ui"},
            {"usage": "/setting status", "description": "Show the settings dashboard without entering the TUI.", "example": "/setting status"},
            {"usage": "/setting mode <mode-name>", "description": "Change the active Reverie operating mode.", "example": "/setting mode writer"},
            {"usage": "/setting model", "description": "Open the standard-model selector from settings.", "example": "/setting model"},
            {"usage": "/setting model <index>", "description": "Switch to a standard model by index or fuzzy name.", "example": "/setting model 2"},
            {"usage": "/setting theme <theme>", "description": "Change the stored theme preset.", "example": "/setting theme ocean"},
            {"usage": "/setting auto-index on|off", "description": "Enable or disable automatic indexing on cold starts.", "example": "/setting auto-index off"},
            {"usage": "/setting status-line on|off", "description": "Enable or disable the live status line.", "example": "/setting status-line on"},
            {"usage": "/setting tool-output compact|condensed|full", "description": "Choose how completed tool results are collapsed after live execution finishes.", "example": "/setting tool-output condensed"},
            {"usage": "/setting thinking full|compact|hidden", "description": "Choose whether streamed reasoning stays fully visible, is compacted, or is hidden.", "example": "/setting thinking full"},
            {"usage": "/setting stream on|off", "description": "Enable or disable streaming responses.", "example": "/setting stream off"},
            {"usage": "/setting timeout <seconds>", "description": "Set the default API timeout.", "example": "/setting timeout 120"},
            {"usage": "/setting retries <count>", "description": "Set the retry budget for recoverable API failures.", "example": "/setting retries 5"},
            {"usage": "/setting debug on|off", "description": "Toggle debug logging for API requests.", "example": "/setting debug on"},
            {"usage": "/setting workspace on|off", "description": "Switch between workspace-local and global config storage.", "example": "/setting workspace on"},
            {"usage": "/setting rules", "description": "Open the quick rules editor from the settings command.", "example": "/setting rules"},
        ],
        "examples": ["/setting", "/settings", "/setting status", "/setting thinking full", "/setting tool-output condensed", "/setting mode spec-driven", "/setting timeout 120"],
    },
    "rules": {
        "command": "/rules",
        "section": "Project & Rules",
        "summary": "List, edit, add, or remove custom rules.",
        "detail": "Rules are applied to the session prompt. Use `/rules edit` for direct file editing or `/rules add` for quick one-line entries.",
        "overview": "list, edit, add [text], remove/delete <n>",
        "subcommands": [
            {"usage": "/rules", "description": "List all custom rules."},
            {"usage": "/rules list", "description": "Explicit list view."},
            {"usage": "/rules edit", "description": "Open `rules.txt` in the default editor and reload it after confirmation."},
            {"usage": "/rules add", "description": "Prompt for a new one-line rule interactively."},
            {"usage": "/rules add <text>", "description": "Add a new rule directly from the command line."},
            {"usage": "/rules remove <number>", "description": "Remove a rule by its list index."},
            {"usage": "/rules delete <number>", "description": "Alias of `/rules remove <number>`."},
        ],
        "examples": ["/rules", "/rules add Always run tests before finalizing", "/rules remove 2"],
    },
    "workspace": {
        "command": "/workspace",
        "section": "Project & Rules",
        "summary": "Control workspace-local config mode and copy config between global and local scopes.",
        "detail": "Use this when you want per-project config instead of a single global config file.",
        "overview": "status, enable, disable, copy-to-workspace, copy-to-global",
        "subcommands": [
            {"usage": "/workspace", "description": "Show workspace-config status and available actions."},
            {"usage": "/workspace status", "description": "Explicit status view."},
            {"usage": "/workspace enable", "description": "Enable workspace-local configuration mode."},
            {"usage": "/workspace disable", "description": "Disable workspace-local configuration and return to global config."},
            {"usage": "/workspace copy-to-workspace", "description": "Copy the global config into the workspace config file."},
            {"usage": "/workspace copy-to-global", "description": "Copy the workspace config into the global config file."},
        ],
        "examples": ["/workspace", "/workspace enable", "/workspace copy-to-workspace"],
    },
    "sessions": {
        "command": "/sessions",
        "section": "Sessions & Recovery",
        "summary": "Open the interactive session browser for create, load, or delete actions.",
        "detail": "This command is prompt-driven rather than subcommand-driven: it shows the session table, then waits for an action.",
        "overview": "open ui; actions: n, d, <number>",
        "subcommands": [
            {"usage": "/sessions", "description": "Open the session browser."},
            {"usage": "Action: n", "description": "Create a new session after the browser opens."},
            {"usage": "Action: <number>", "description": "Load a session by its listed index."},
            {"usage": "Action: d", "description": "Delete a session after entering its index."},
        ],
        "examples": ["/sessions"],
    },
    "history": {
        "command": "/history",
        "section": "Sessions & Recovery",
        "summary": "Show recent conversation history from the active agent.",
        "detail": "Without a number it prints the full retained history. With a number it limits the output to the latest N entries.",
        "overview": "[count]",
        "subcommands": [
            {"usage": "/history", "description": "Show all retained conversation history."},
            {"usage": "/history <count>", "description": "Show only the most recent `<count>` messages."},
        ],
        "examples": ["/history", "/history 20"],
    },
    "rollback": {
        "command": "/rollback",
        "section": "Sessions & Recovery",
        "summary": "Rollback to a previous question, tool call, or checkpoint.",
        "detail": "Bare `/rollback` opens the interactive rollback UI. You can also target common rollback modes directly from the command line.",
        "overview": "interactive, question, tool, <checkpoint-id>",
        "subcommands": [
            {"usage": "/rollback", "description": "Open the interactive rollback UI."},
            {"usage": "/rollback question", "description": "Rollback to the previous user question."},
            {"usage": "/rollback tool", "description": "Rollback to the previous tool call."},
            {"usage": "/rollback <checkpoint-id>", "description": "Rollback directly to a specific checkpoint id."},
        ],
        "examples": ["/rollback", "/rollback question", "/rollback cp_20260311_001"],
    },
    "undo": {
        "command": "/undo",
        "section": "Sessions & Recovery",
        "summary": "Undo the last rollback operation.",
        "detail": "Only available when the rollback manager has something to undo.",
        "overview": "undo last rollback",
        "subcommands": [
            {"usage": "/undo", "description": "Undo the most recent rollback action."},
        ],
        "examples": ["/undo"],
    },
    "redo": {
        "command": "/redo",
        "section": "Sessions & Recovery",
        "summary": "Redo the last undone rollback operation.",
        "detail": "Only available after an undo and while the redo stack still exists.",
        "overview": "redo last undo",
        "subcommands": [
            {"usage": "/redo", "description": "Redo the most recently undone rollback action."},
        ],
        "examples": ["/redo"],
    },
    "checkpoints": {
        "command": "/checkpoints",
        "section": "Sessions & Recovery",
        "summary": "Browse checkpoints and restore one interactively.",
        "detail": "This opens a checkpoint selector rather than accepting textual subcommands.",
        "overview": "interactive selector",
        "subcommands": [
            {"usage": "/checkpoints", "description": "Open the checkpoint selector and restore a checkpoint interactively."},
        ],
        "examples": ["/checkpoints"],
    },
    "operations": {
        "command": "/operations",
        "section": "Sessions & Recovery",
        "summary": "Show operation history and rollback statistics.",
        "detail": "Use this to inspect the recent operation log, counts, modified files, and undo/redo availability.",
        "overview": "history & stats",
        "subcommands": [
            {"usage": "/operations", "description": "Show recent operations and summary statistics."},
        ],
        "examples": ["/operations"],
    },
    "gdd": {
        "command": "/gdd",
        "section": "Game",
        "summary": "Create, inspect, validate, version, and export the game design document.",
        "detail": "Primarily intended for `reverie-gamer`, but available whenever the game tools are installed. The command now covers validation, metadata, backups, and export work in addition to basic viewing.",
        "overview": "create, view, summary, validate, append, metadata, version, export",
        "subcommands": [
            {"usage": "/gdd", "description": "View the current game design document."},
            {"usage": "/gdd view", "description": "Explicit view action."},
            {"usage": "/gdd create", "description": "Generate a new game design document interactively."},
            {"usage": "/gdd summary", "description": "Generate a summarized view of the GDD."},
            {"usage": "/gdd validate", "description": "Run structure and completeness checks against the current GDD."},
            {"usage": "/gdd append", "description": "Add a new section to the current GDD interactively."},
            {"usage": "/gdd metadata", "description": "Update metadata like status, version, or owner."},
            {"usage": "/gdd version list", "description": "List existing GDD backups."},
            {"usage": "/gdd version create", "description": "Create a timestamped GDD backup."},
            {"usage": "/gdd export html", "description": "Export the current GDD to HTML."},
        ],
        "examples": ["/gdd", "/gdd create", "/gdd validate", "/gdd version create", "/gdd export html"],
    },
    "assets": {
        "command": "/assets",
        "section": "Game",
        "summary": "Inspect and manage game assets, dependencies, optimization, and manifests.",
        "detail": "The asset command now covers grouped listing, manifest generation, missing references, unused assets, dependency graphs, compression guidance, naming checks, and sprite atlas planning.",
        "overview": "list, analyze, manifest, missing, unused, graph, compress, size, naming, atlas, import",
        "subcommands": [
            {"usage": "/assets", "description": "Show all detected assets grouped by type."},
            {"usage": "/assets all", "description": "Explicit all-assets view."},
            {"usage": "/assets sprite", "description": "Show only sprite assets."},
            {"usage": "/assets audio", "description": "Show only audio assets."},
            {"usage": "/assets model", "description": "Show only 3D model assets."},
            {"usage": "/assets animation", "description": "Show only animation assets."},
            {"usage": "/assets analyze", "description": "Summarize asset counts, size, extensions, and largest files."},
            {"usage": "/assets manifest", "description": "Generate the asset manifest file."},
            {"usage": "/assets missing", "description": "Find asset references in code or data that do not exist on disk."},
            {"usage": "/assets unused", "description": "Find assets that do not appear to be referenced."},
            {"usage": "/assets graph", "description": "Analyze asset dependency usage across code and data."},
            {"usage": "/assets compress", "description": "Get compression and optimization recommendations."},
            {"usage": "/assets size", "description": "Estimate disk and runtime footprint for assets."},
            {"usage": "/assets naming", "description": "Validate asset names against a regex pattern."},
            {"usage": "/assets atlas", "description": "Build a sprite atlas plan."},
        ],
        "examples": ["/assets", "/assets analyze", "/assets graph", "/assets compress", "/assets atlas 2048"],
    },
    "blueprint": {
        "command": "/blueprint",
        "section": "Game",
        "summary": "Create, inspect, analyze, and export structured game blueprints.",
        "detail": "This is the CLI surface for the new design orchestrator. Use it to define scope, systems, and vertical-slice plans before broad implementation work.",
        "overview": "view, create, analyze, slice, export, expand",
        "aliases": ["/bp"],
        "subcommands": [
            {"usage": "/blueprint", "description": "Show the current blueprint overview if one exists."},
            {"usage": "/blueprint create", "description": "Create a new game blueprint interactively."},
            {"usage": "/blueprint analyze", "description": "Run scope and complexity analysis on the current blueprint."},
            {"usage": "/blueprint slice", "description": "Generate a vertical-slice plan from the current blueprint."},
            {"usage": "/blueprint export", "description": "Export the current blueprint to Markdown."},
            {"usage": "/blueprint expand <system_name>", "description": "Expand one gameplay system inside the blueprint.", "example": "/blueprint expand Combat"},
        ],
        "examples": ["/blueprint", "/blueprint create", "/blueprint analyze", "/blueprint slice", "/bp expand Progression"],
    },
    "scaffold": {
        "command": "/scaffold",
        "section": "Game",
        "summary": "Plan or create the engine-aware project foundation for a game project.",
        "detail": "Use this after the blueprint exists to create a stronger runtime, data, tests, tooling, and content-pipeline structure.",
        "overview": "plan, create, modules, pipeline",
        "subcommands": [
            {"usage": "/scaffold", "description": "Plan the recommended project structure."},
            {"usage": "/scaffold plan", "description": "Explicit structure-plan action."},
            {"usage": "/scaffold create", "description": "Create the project foundation and starter files."},
            {"usage": "/scaffold modules", "description": "Generate the module map document."},
            {"usage": "/scaffold pipeline", "description": "Generate the content-pipeline document."},
        ],
        "examples": ["/scaffold", "/scaffold create", "/scaffold modules", "/scaffold pipeline"],
    },
    "engine": {
        "command": "/engine",
        "section": "Game",
        "summary": "Create, inspect, validate, benchmark, package, and smoke-test projects powered by Reverie Engine.",
        "detail": "This is the direct CLI surface for Reverie's built-in runtime. Use it when you want a first-party engine workflow without relying on an external engine.",
        "overview": "profile, create, sample, run, validate, smoke, video, renpy, health, benchmark, package, test",
        "subcommands": [
            {"usage": "/engine", "description": "Show the current Reverie Engine project profile."},
            {"usage": "/engine profile", "description": "Explicit profile and capability inspection."},
            {"usage": "/engine create", "description": "Create a Reverie Engine project skeleton interactively."},
            {"usage": "/engine sample 2d_platformer", "description": "Materialize the built-in 2D platformer sample."},
            {"usage": "/engine run", "description": "Run the current entry scene and emit a runtime log."},
            {"usage": "/engine validate", "description": "Validate the current engine project layout and schemas."},
            {"usage": "/engine smoke", "description": "Run the deterministic smoke path and write telemetry."},
            {"usage": "/engine video mp4", "description": "Export a playblast-style frame sequence or encoded video from the current project."},
            {"usage": "/engine renpy <script_path> [conversation_id] [entry_label]", "description": "Import a practical subset of Ren'Py `.rpy` dialogue into `data/content/dialogue.yaml`."},
            {"usage": "/engine health", "description": "Build a project health report with score and recommendations."},
            {"usage": "/engine benchmark", "description": "Measure scene instantiation and AI authoring baseline latency."},
            {"usage": "/engine package", "description": "Create a portable runtime package zip for the current engine project."},
            {"usage": "/engine test", "description": "Validate the current project and then run the smoke path."},
        ],
        "examples": ["/engine", "/engine create", "/engine sample iso_adventure", "/engine validate", "/engine smoke", "/engine video mp4", "/engine renpy scripts/dialogue.rpy branching_flow branching", "/engine health", "/engine benchmark", "/engine package", "/engine test"],
    },
    "modeling": {
        "command": "/modeling",
        "section": "Game",
        "summary": "Run the Reverie-Gamer-only built-in modeling workflow, including workspace setup, primitive generation, headless `.bbmodel` validation/export, model import, registry sync, and optional Ashfox MCP calls.",
        "detail": "This command is exclusive to `reverie-gamer` mode. It standardizes Blockbench-style source files under `assets/models/source`, runtime imports under `assets/models/runtime`, generated registries under `data/models`, built-in primitive GLTF generation with preview renders, headless `.bbmodel` validation/export for cuboid files, and optional Ashfox MCP operations against Reverie's built-in `ashfox` server entry when a live Blockbench session is available.",
        "overview": "status, setup, sync, stub, primitive, validate-bbmodel, export-bbmodel, import, ashfox tools|capabilities|state|validate|export|call",
        "subcommands": [
            {"usage": "/modeling", "description": "Inspect the current modeling stack, workspace manifests, and discovered model counts."},
            {"usage": "/modeling setup", "description": "Create the modeling pipeline folders, docs, and pipeline manifests."},
            {"usage": "/modeling sync", "description": "Regenerate `data/models/model_registry.yaml` from source/runtime model folders."},
            {"usage": "/modeling stub <model_name>", "description": "Create a starter `.bbmodel` inside `assets/models/source/`."},
            {"usage": "/modeling primitive <type> <model_name>", "description": "Generate a built-in primitive runtime model plus preview into the Reverie layout."},
            {"usage": "/modeling validate-bbmodel <source_bbmodel>", "description": "Validate a Blockbench `.bbmodel` source file without requiring the desktop app or Ashfox plugin."},
            {"usage": "/modeling export-bbmodel <source_bbmodel> [dest_name]", "description": "Convert a supported cuboid `.bbmodel` into a runtime `.gltf`, preview, and registry entry."},
            {"usage": "/modeling import <runtime_export> [source_bbmodel] [preview_image] [dest_name]", "description": "Import a runtime model export plus optional source model and preview into the standard Reverie layout."},
            {"usage": "/modeling ashfox tools", "description": "List the Ashfox MCP tools discovered through Reverie's built-in MCP runtime."},
            {"usage": "/modeling ashfox capabilities", "description": "Fetch Ashfox capability metadata through the built-in MCP server entry."},
            {"usage": "/modeling ashfox state [summary|full]", "description": "Read the current Blockbench project state through Ashfox MCP."},
            {"usage": "/modeling ashfox validate", "description": "Run Ashfox validation against the active model project."},
            {"usage": "/modeling ashfox export <format> <dest_path>", "description": "Ask Ashfox to export the active project into a runtime artifact."},
            {"usage": "/modeling ashfox call <tool_name> <json_arguments>", "description": "Call any Ashfox tool directly with raw JSON arguments."},
        ],
        "examples": ["/modeling", "/modeling setup", "/modeling stub hero_body", "/modeling primitive box hero_crate", "/modeling validate-bbmodel assets/models/source/hero_body.bbmodel", "/modeling export-bbmodel assets/models/source/hero_body.bbmodel hero_body", "/modeling import exports/hero.glb assets/models/source/hero_body.bbmodel", "/modeling ashfox tools", "/modeling ashfox validate", "/modeling ashfox export gltf assets/models/runtime/hero.glb"],
    },
    "blender": {
        "command": "/blender",
        "section": "Game",
        "summary": "Run Reverie's built-in Blender modeling workflow without configuring an external MCP server or Skill.",
        "detail": "This command wraps the `blender_modeling_workbench` built-in tool. It detects Blender, creates the standard modeling workspace, generates auditable Blender Python authoring scripts from briefs, optionally runs Blender in background mode, saves `.blend` sources, exports `.glb`/`.gltf` runtime assets, renders previews, audits completed assets for production gates, consumes automatic repair queues, and syncs `data/models/model_registry.yaml`. Briefs that describe anime-action playable characters can select the `anime_action_character` preset for layered character blockouts with weapon, rig, LOD, and material markers. Final/AAA character briefs select `production_character_pipeline`, which emits production PBR texture sets, art-readiness reports, material tuning, skinning, animation, IK, collision, LOD, asset-card, production-stage, and black-box iteration manifests.",
        "overview": "status, setup, script, create, run, validate, audit, repair, sync",
        "subcommands": [
            {"usage": "/blender status", "description": "Inspect Blender installation, generated scripts, model plans, and model counts."},
            {"usage": "/blender setup", "description": "Create Blender source/script/plan folders in the standard modeling workspace."},
            {"usage": "/blender script <model_name> <brief>", "description": "Generate a model plan and Blender Python script without running Blender."},
            {"usage": "/blender create <model_name> <brief>", "description": "Generate and run Blender to save `.blend`, export `.glb`, render a preview, and sync the registry."},
            {"usage": "/blender run <script_path>", "description": "Run a workspace-local Blender Python script through Blender background mode."},
            {"usage": "/blender validate <script_path>", "description": "Validate a Blender script with Reverie's conservative static scan."},
            {"usage": "/blender audit <model_name>", "description": "Audit generated `.blend`, runtime export, texture set, validation report, production manifest, black-box iteration plan, material/skin/animation manifests, rig, IK, weights, sockets, collision proxies, and LOD gates."},
            {"usage": "/blender repair <model_name> [max_iterations]", "description": "Consume the model's automatic repair queue, regenerate and rerun the authoring script, re-audit, and write repair history."},
            {"usage": "/blender sync", "description": "Regenerate `data/models/model_registry.yaml` from source/runtime model folders."},
        ],
        "examples": ["/blender status", "/blender setup", "/blender script hero \"Genshin / ZZZ style anime action playable character with jacket and weapon\"", "/blender script relic \"fantasy crystal shrine relic\"", "/blender create sci_crate \"sci-fi crate with emissive panels\"", "/blender audit sci_crate", "/blender repair sci_crate 2", "/blender run assets/models/source/blender/scripts/relic.py", "/blender sync"],
    },
    "playtest": {
        "command": "/playtest",
        "section": "Game",
        "summary": "Create playtest plans, telemetry schemas, quality gates, and analyze playtest artifacts.",
        "detail": "This command exposes the playtest lab so design and implementation can stay tied to real feedback, telemetry, and verification thresholds.",
        "overview": "plan, telemetry, gates, analyze, feedback",
        "aliases": ["/pt"],
        "subcommands": [
            {"usage": "/playtest", "description": "Create a playtest plan interactively."},
            {"usage": "/playtest plan", "description": "Explicit playtest-plan action."},
            {"usage": "/playtest telemetry", "description": "Generate the telemetry schema."},
            {"usage": "/playtest gates", "description": "Generate quality gates for milestone checks."},
            {"usage": "/playtest analyze <session_log_path>", "description": "Analyze a session log file.", "example": "/playtest analyze playtest/logs/session.json"},
            {"usage": "/playtest feedback <feedback_path>", "description": "Synthesize feedback from a file.", "example": "/playtest feedback playtest/feedback.txt"},
        ],
        "examples": ["/playtest", "/playtest telemetry", "/playtest gates", "/pt analyze playtest/logs/session.json"],
    },
}


def normalize_help_topic(value: str) -> str:
    """Resolve a help query to a canonical help topic key."""
    raw = str(value or "").strip()
    if not raw:
        return ""

    normalized = raw.lstrip("/").strip().lower().replace("-", "_")
    primary = normalized.split()[0] if normalized.split() else ""
    compact = normalized.replace(" ", "")
    alias_map = {
        "gemini": "geminicli",
        "geminicli": "geminicli",
        "gcli": "geminicli",
        "ms": "modelscope",
        "modelscope": "modelscope",
        "model_scope": "modelscope",
        "modelscopecli": "modelscope",
        "ce": "ce",
        "contextengine": "ce",
        "context": "ce",
        "settings": "setting",
        "quit": "exit",
        "harness": "doctor",
        "bp": "blueprint",
        "pt": "playtest",
    }

    for candidate in (compact, primary):
        if candidate in HELP_TOPICS:
            return candidate
        if candidate in alias_map:
            return alias_map[candidate]
    return ""


def build_command_completion_map() -> Dict[str, str]:
    """Build the command-completion descriptions from the shared help catalog."""
    completions: Dict[str, str] = {}
    for topic in HELP_TOPICS.values():
        command = str(topic.get("command", "")).strip()
        summary = str(topic.get("summary", "")).strip()
        if command and summary:
            completions[command] = summary
        for alias in topic.get("aliases", []) or []:
            alias_text = str(alias).strip()
            if alias_text and alias_text not in completions:
                completions[alias_text] = f"Alias of {command}"
    return completions
