//! Skill executor for running skills in the context of a project.

use crate::loader::SkillLoader;
use crate::types::*;
use anyhow::{anyhow, Result};
use tracing::{debug, info, warn};

/// Skill executor
pub struct SkillExecutor {
    /// Skill loader
    loader: SkillLoader,
}

impl SkillExecutor {
    /// Create a new skill executor
    pub fn new(loader: SkillLoader) -> Self {
        Self { loader }
    }

    /// Execute a skill by name
    pub async fn execute(
        &self,
        name: &str,
        context: SkillInvocationContext,
    ) -> Result<SkillExecutionResult> {
        let skill = self
            .loader
            .get(name)
            .await
            .ok_or_else(|| anyhow!("Skill not found: {}", name))?;

        info!("Executing skill: {}", name);

        let instructions = parse_skill_instructions(&skill.content)?;
        let result = self.run_skill(&skill, &instructions, context).await?;

        Ok(result)
    }

    /// Run a skill with parsed instructions
    async fn run_skill(
        &self,
        skill: &Skill,
        instructions: &[SkillStep],
        context: SkillInvocationContext,
    ) -> Result<SkillExecutionResult> {
        let mut output = String::new();
        let mut errors = Vec::new();

        for (i, step) in instructions.iter().enumerate() {
            debug!(
                "Executing step {}/{}: {}",
                i + 1,
                instructions.len(),
                step.description
            );

            match self.execute_step(step, &context).await {
                Ok(step_output) => {
                    output.push_str(&format!("Step {}: {}\n", i + 1, step.description));
                    output.push_str(&step_output);
                    output.push('\n');
                }
                Err(e) => {
                    errors.push(format!("Step {}: {}", i + 1, e));
                    warn!("Step failed: {}", e);
                }
            }
        }

        Ok(SkillExecutionResult {
            skill_name: skill.name.clone(),
            success: errors.is_empty(),
            output,
            errors,
        })
    }

    /// Execute a single skill step
    async fn execute_step(
        &self,
        step: &SkillStep,
        context: &SkillInvocationContext,
    ) -> Result<String> {
        let mut output = String::new();

        // Execute command if present
        if let Some(cmd) = &step.command {
            let expanded = Self::expand_variables(cmd, context);
            debug!("Running command: {}", expanded);
            let result = tokio::process::Command::new(if cfg!(windows) { "cmd" } else { "sh" })
                .args(if cfg!(windows) {
                    vec!["/C", &expanded]
                } else {
                    vec!["-c", &expanded]
                })
                .current_dir(&context.cwd)
                .output()
                .await;
            match result {
                Ok(cmd_output) => {
                    let stdout = String::from_utf8_lossy(&cmd_output.stdout);
                    let stderr = String::from_utf8_lossy(&cmd_output.stderr);
                    if !stdout.is_empty() {
                        output.push_str(&stdout);
                    }
                    if !stderr.is_empty() {
                        output.push_str("[stderr] ");
                        output.push_str(&stderr);
                    }
                    if !cmd_output.status.success() {
                        return Err(anyhow!(
                            "Command exited with code {}: {}",
                            cmd_output.status.code().unwrap_or(-1),
                            stderr.trim()
                        ));
                    }
                }
                Err(e) => return Err(anyhow!("Failed to run command '{}': {}", expanded, e)),
            }
        }

        // Read file if specified
        if let Some(file_path) = &step.read_file {
            let expanded = Self::expand_variables(file_path, context);
            let full_path = context.project_root.join(&expanded);
            match std::fs::read_to_string(&full_path) {
                Ok(content) => {
                    output.push_str(&format!("[read {}] {} bytes\n", expanded, content.len()));
                    output.push_str(&content);
                }
                Err(e) => return Err(anyhow!("Failed to read '{}': {}", expanded, e)),
            }
        }

        // Write file if specified
        if let Some(file_path) = &step.write_file {
            let expanded = Self::expand_variables(file_path, context);
            let full_path = context.project_root.join(&expanded);
            if let Some(parent) = full_path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            // Write the accumulated output from previous sub-steps as the file content
            let content = if output.is_empty() {
                format!("# Generated by skill: {}\n", context.skill_name)
            } else {
                output.clone()
            };
            std::fs::write(&full_path, &content)?;
            output.push_str(&format!("[wrote {}] {} bytes\n", expanded, content.len()));
        }

        // If no explicit sub-operations, just report the description
        if step.command.is_none() && step.read_file.is_none() && step.write_file.is_none() {
            output.push_str(&format!("Executed: {}", step.description));
        }

        Ok(output)
    }

    /// Expand variables like {{project_root}}, {{cwd}}, {{skill_name}} in a string
    fn expand_variables(input: &str, context: &SkillInvocationContext) -> String {
        let mut result = input.to_string();
        result = result.replace("{{project_root}}", &context.project_root.to_string_lossy());
        result = result.replace("{{cwd}}", &context.cwd.to_string_lossy());
        result = result.replace("{{skill_name}}", &context.skill_name);
        for (key, value) in &context.arguments {
            result = result.replace(&format!("{{{{{key}}}}}"), value);
        }
        result
    }

    /// List all available skills
    pub async fn list_skills(&self) -> Vec<Skill> {
        self.loader.list_all().await
    }

    /// Search skills
    pub async fn search_skills(&self, pattern: &str) -> Vec<Skill> {
        self.loader.search(pattern).await
    }
}

/// A step in a skill
#[derive(Debug, Clone)]
pub struct SkillStep {
    /// Step number
    pub number: usize,
    /// Step description/instruction
    pub description: String,
    /// Optional command to execute
    pub command: Option<String>,
    /// Optional file to read
    pub read_file: Option<String>,
    /// Optional file to write
    pub write_file: Option<String>,
}

/// Result of skill execution
#[derive(Debug, Clone)]
pub struct SkillExecutionResult {
    /// Name of the executed skill
    pub skill_name: String,
    /// Whether execution succeeded
    pub success: bool,
    /// Execution output
    pub output: String,
    /// Errors encountered
    pub errors: Vec<String>,
}

/// Parse skill content into structured steps
fn parse_skill_instructions(content: &str) -> Result<Vec<SkillStep>> {
    let mut steps = Vec::new();
    let mut current_step = 0;
    let mut current_desc = String::new();
    let mut current_command: Option<String> = None;
    let mut current_read_file: Option<String> = None;
    let mut current_write_file: Option<String> = None;
    let mut in_code_block = false;
    let mut code_block_lang = String::new();
    let mut code_block_content = String::new();

    for line in content.lines() {
        let trimmed = line.trim();

        // Track fenced code blocks
        if trimmed.starts_with("```") {
            if in_code_block {
                // End of code block — check if it's a command
                if matches!(
                    code_block_lang.as_str(),
                    "bash" | "sh" | "shell" | "cmd" | "powershell" | "ps1"
                ) {
                    current_command = Some(code_block_content.trim().to_string());
                }
                in_code_block = false;
                code_block_content.clear();
                code_block_lang.clear();
            } else {
                // Start of code block
                in_code_block = true;
                code_block_lang = trimmed.strip_prefix("```").unwrap_or("").trim().to_string();
            }
            continue;
        }

        if in_code_block {
            if !code_block_content.is_empty() {
                code_block_content.push('\n');
            }
            code_block_content.push_str(line);
            continue;
        }

        // Check for read/write directives
        if let Some(path) = trimmed
            .strip_prefix("@read ")
            .or_else(|| trimmed.strip_prefix("read:"))
        {
            current_read_file = Some(path.trim().to_string());
            continue;
        }
        if let Some(path) = trimmed
            .strip_prefix("@write ")
            .or_else(|| trimmed.strip_prefix("write:"))
        {
            current_write_file = Some(path.trim().to_string());
            continue;
        }

        // Check for numbered step headers
        if let Some(rest) = trimmed
            .strip_prefix(|c: char| c.is_ascii_digit())
            .and_then(|r| r.strip_prefix('.').or(Some(r)))
        {
            // This might be a new numbered step — verify it looks like one
            let rest = rest.trim_start_matches(|c: char| c.is_ascii_digit());
            let rest = rest.strip_prefix('.').unwrap_or(rest).trim();
            if !rest.is_empty() || !current_desc.is_empty() {
                // Flush previous step
                if !current_desc.is_empty() {
                    steps.push(SkillStep {
                        number: current_step,
                        description: current_desc.trim().to_string(),
                        command: current_command.take(),
                        read_file: current_read_file.take(),
                        write_file: current_write_file.take(),
                    });
                }
                // Parse step number
                let num_str: String = trimmed.chars().take_while(|c| c.is_ascii_digit()).collect();
                current_step = num_str.parse::<usize>().unwrap_or(current_step + 1);
                current_desc = rest.to_string();
                continue;
            }
        }

        if !trimmed.is_empty() && !trimmed.starts_with('#') {
            if current_desc.is_empty() {
                current_desc = trimmed.to_string();
            } else {
                current_desc.push('\n');
                current_desc.push_str(trimmed);
            }
        }
    }

    if !current_desc.is_empty() {
        steps.push(SkillStep {
            number: current_step,
            description: current_desc.trim().to_string(),
            command: current_command,
            read_file: current_read_file,
            write_file: current_write_file,
        });
    }

    Ok(steps)
}
